/**
 * TanStack Router configuration.
 * Creates the router instance from the auto-generated route tree.
 * The route tree is generated by the router plugin based on file-system routes.
 */

import { createRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen';

/**
 * Application router instance.
 * Provides type-safe navigation and route matching for the entire app.
 */
export const router = createRouter({ routeTree });

/**
 * Module augmentation for TanStack Router.
 * Registers the router type for type-safe hooks like useNavigate and useParams.
 */
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
