/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as BookingImport } from './routes/booking'
import { Route as IndexImport } from './routes/index'
import { Route as BookingsIndexImport } from './routes/bookings.index'
import { Route as AdminIndexImport } from './routes/admin.index'
import { Route as HotelsHotelIdImport } from './routes/hotels.$hotelId'
import { Route as BookingsBookingIdImport } from './routes/bookings.$bookingId'
import { Route as AdminHotelsHotelIdImport } from './routes/admin.hotels.$hotelId'

// Create/Update Routes

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const BookingRoute = BookingImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BookingsIndexRoute = BookingsIndexImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const HotelsHotelIdRoute = HotelsHotelIdImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRoute,
} as any)

const BookingsBookingIdRoute = BookingsBookingIdImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRoute,
} as any)

const AdminHotelsHotelIdRoute = AdminHotelsHotelIdImport.update({
  id: '/admin/hotels/$hotelId',
  path: '/admin/hotels/$hotelId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/hotels/$hotelId': {
      id: '/admin/hotels/$hotelId'
      path: '/admin/hotels/$hotelId'
      fullPath: '/admin/hotels/$hotelId'
      preLoaderRoute: typeof AdminHotelsHotelIdImport
      parentRoute: typeof rootRoute
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdImport
      parentRoute: typeof rootRoute
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin': typeof AdminIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin': typeof AdminIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/login'
    | '/register'
    | '/search'
    | '/admin'
    | '/bookings'
    | '/admin/hotels/$hotelId'
    | '/bookings/$bookingId'
    | '/hotels/$hotelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/login'
    | '/register'
    | '/search'
    | '/admin'
    | '/bookings'
    | '/admin/hotels/$hotelId'
    | '/bookings/$bookingId'
    | '/hotels/$hotelId'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/login'
    | '/register'
    | '/search'
    | '/admin/'
    | '/bookings/'
    | '/admin/hotels/$hotelId'
    | '/bookings/$bookingId'
    | '/hotels/$hotelId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  AdminHotelsHotelIdRoute: typeof AdminHotelsHotelIdRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  AdminIndexRoute: AdminIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  AdminHotelsHotelIdRoute: AdminHotelsHotelIdRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
