/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as RiderImport } from './routes/rider'
import { Route as DriverImport } from './routes/driver'
import { Route as IndexImport } from './routes/index'
import { Route as RiderHistoryImport } from './routes/rider/history'
import { Route as DriverHistoryImport } from './routes/driver/history'
import { Route as DriverEarningsImport } from './routes/driver/earnings'

// Create Virtual Loaders

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const RiderRoute = RiderImport.update({
  path: '/rider',
  getParentRoute: () => rootRoute,
} as any)

const DriverRoute = DriverImport.update({
  path: '/driver',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RiderHistoryRoute = RiderHistoryImport.update({
  path: '/rider/history',
  getParentRoute: () => rootRoute,
} as any)

const DriverHistoryRoute = DriverHistoryImport.update({
  path: '/driver/history',
  getParentRoute: () => rootRoute,
} as any)

const DriverEarningsRoute = DriverEarningsImport.update({
  path: '/driver/earnings',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/rider': {
      preLoaderRoute: typeof RiderImport
      parentRoute: typeof rootRoute
    }
    '/driver': {
      preLoaderRoute: typeof DriverImport
      parentRoute: typeof rootRoute
    }
    '/rider/history': {
      preLoaderRoute: typeof RiderHistoryImport
      parentRoute: typeof rootRoute
    }
    '/driver/history': {
      preLoaderRoute: typeof DriverHistoryImport
      parentRoute: typeof rootRoute
    }
    '/driver/earnings': {
      preLoaderRoute: typeof DriverEarningsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  RegisterRoute,
  RiderRoute,
  DriverRoute,
  RiderHistoryRoute,
  DriverHistoryRoute,
  DriverEarningsRoute,
])

/* prettier-ignore-end */
