import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
p.on('console', m => console.log('CONSOLE', m.type(), m.text()));
p.on('pageerror', e => console.log('PAGEERROR', e.message));
p.on('requestfailed', r => console.log('REQFAIL', r.method(), r.url(), r.failure()?.errorText));
p.on('response', r => { if (r.url().includes('/api/')) console.log('RESP', r.status(), r.request().method(), r.url()); });
await p.goto('http://localhost:5173/login', { waitUntil: 'networkidle' });
await p.fill("input[type='email']", 'alice@example.com');
await p.fill("input[type='password']", 'password123');
console.log('--- filled; clicking submit ---');
await p.click("button[type='submit']");
await p.waitForTimeout(3000);
console.log('FINAL URL:', p.url());
const banner = await p.$('.bg-red-50, .text-red-600');
console.log('ERROR BANNER:', banner ? (await banner.textContent()).trim() : '(none)');
const pw = await p.$("input[type='password']");
console.log('PASSWORD FIELD STILL PRESENT:', !!pw);
await b.close();
