/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as ProfileImport } from './routes/profile'
import { Route as PreferencesImport } from './routes/preferences'
import { Route as MatchesImport } from './routes/matches'
import { Route as LoginImport } from './routes/login'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as ChatMatchIdImport } from './routes/chat.$matchId'
import { Route as AdminUsersImport } from './routes/admin/users'

// Create Virtual Routes

const ChatMatchIdLazyImport = createFileRoute('/chat/$matchId')()

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const PreferencesRoute = PreferencesImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRoute,
} as any)

const MatchesRoute = MatchesImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChatMatchIdRoute = ChatMatchIdImport.update({
  id: '/chat/$matchId',
  path: '/chat/$matchId',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/admin/users',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesImport
      parentRoute: typeof rootRoute
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/chat/$matchId': {
      id: '/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof ChatMatchIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
  '/admin/users': typeof AdminUsersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
  '/admin/users': typeof AdminUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
  '/admin/users': typeof AdminUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/matches'
    | '/preferences'
    | '/profile'
    | '/register'
    | '/chat/$matchId'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/matches'
    | '/preferences'
    | '/profile'
    | '/register'
    | '/chat/$matchId'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/matches'
    | '/preferences'
    | '/profile'
    | '/register'
    | '/chat/$matchId'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ChatMatchIdRoute: typeof ChatMatchIdRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ChatMatchIdRoute: ChatMatchIdRoute,
  AdminUsersRoute: AdminUsersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
