/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ProjectProjectIdTablesRouteImport } from './routes/project.$projectId.tables'
import { Route as ProjectProjectIdSqlRouteImport } from './routes/project.$projectId.sql'
import { Route as ProjectProjectIdSettingsRouteImport } from './routes/project.$projectId.settings'
import { Route as ProjectProjectIdAuthRouteImport } from './routes/project.$projectId.auth'
import { Route as ProjectProjectIdTablesTableNameRouteImport } from './routes/project.$projectId.tables_.$tableName'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdTablesRoute = ProjectProjectIdTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSqlRoute = ProjectProjectIdSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSettingsRoute =
  ProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdAuthRoute = ProjectProjectIdAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdTablesTableNameRoute =
  ProjectProjectIdTablesTableNameRouteImport.update({
    id: '/tables_/$tableName',
    path: '/tables/$tableName',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/auth': typeof ProjectProjectIdAuthRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/sql': typeof ProjectProjectIdSqlRoute
  '/project/$projectId/tables': typeof ProjectProjectIdTablesRoute
  '/project/$projectId/tables/$tableName': typeof ProjectProjectIdTablesTableNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/auth': typeof ProjectProjectIdAuthRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/sql': typeof ProjectProjectIdSqlRoute
  '/project/$projectId/tables': typeof ProjectProjectIdTablesRoute
  '/project/$projectId/tables/$tableName': typeof ProjectProjectIdTablesTableNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/auth': typeof ProjectProjectIdAuthRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/sql': typeof ProjectProjectIdSqlRoute
  '/project/$projectId/tables': typeof ProjectProjectIdTablesRoute
  '/project/$projectId/tables_/$tableName': typeof ProjectProjectIdTablesTableNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/project/$projectId'
    | '/project/$projectId/auth'
    | '/project/$projectId/settings'
    | '/project/$projectId/sql'
    | '/project/$projectId/tables'
    | '/project/$projectId/tables/$tableName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/project/$projectId'
    | '/project/$projectId/auth'
    | '/project/$projectId/settings'
    | '/project/$projectId/sql'
    | '/project/$projectId/tables'
    | '/project/$projectId/tables/$tableName'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/project/$projectId'
    | '/project/$projectId/auth'
    | '/project/$projectId/settings'
    | '/project/$projectId/sql'
    | '/project/$projectId/tables'
    | '/project/$projectId/tables_/$tableName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/tables': {
      id: '/project/$projectId/tables'
      path: '/tables'
      fullPath: '/project/$projectId/tables'
      preLoaderRoute: typeof ProjectProjectIdTablesRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/sql': {
      id: '/project/$projectId/sql'
      path: '/sql'
      fullPath: '/project/$projectId/sql'
      preLoaderRoute: typeof ProjectProjectIdSqlRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings': {
      id: '/project/$projectId/settings'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof ProjectProjectIdSettingsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/auth': {
      id: '/project/$projectId/auth'
      path: '/auth'
      fullPath: '/project/$projectId/auth'
      preLoaderRoute: typeof ProjectProjectIdAuthRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/tables_/$tableName': {
      id: '/project/$projectId/tables_/$tableName'
      path: '/tables/$tableName'
      fullPath: '/project/$projectId/tables/$tableName'
      preLoaderRoute: typeof ProjectProjectIdTablesTableNameRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdAuthRoute: typeof ProjectProjectIdAuthRoute
  ProjectProjectIdSettingsRoute: typeof ProjectProjectIdSettingsRoute
  ProjectProjectIdSqlRoute: typeof ProjectProjectIdSqlRoute
  ProjectProjectIdTablesRoute: typeof ProjectProjectIdTablesRoute
  ProjectProjectIdTablesTableNameRoute: typeof ProjectProjectIdTablesTableNameRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdAuthRoute: ProjectProjectIdAuthRoute,
  ProjectProjectIdSettingsRoute: ProjectProjectIdSettingsRoute,
  ProjectProjectIdSqlRoute: ProjectProjectIdSqlRoute,
  ProjectProjectIdTablesRoute: ProjectProjectIdTablesRoute,
  ProjectProjectIdTablesTableNameRoute: ProjectProjectIdTablesTableNameRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
