/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Exports

const TransactionsLazyImport = createFileRoute('/transactions')()
const TestPaymentLazyImport = createFileRoute('/test-payment')()
const RefundsLazyImport = createFileRoute('/refunds')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const TransactionsIdLazyImport = createFileRoute('/transactions/$id')()

// Create/Update Routes

const TransactionsLazyRoute = TransactionsLazyImport.update({
  path: '/transactions',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/transactions').then((d) => d.Route))

const TestPaymentLazyRoute = TestPaymentLazyImport.update({
  path: '/test-payment',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/test-payment').then((d) => d.Route))

const RefundsLazyRoute = RefundsLazyImport.update({
  path: '/refunds',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/refunds').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

const TransactionsIdLazyRoute = TransactionsIdLazyImport.update({
  path: '/transactions/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/transactions.$id').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/refunds': {
      preLoaderRoute: typeof RefundsLazyImport
      parentRoute: typeof rootRoute
    }
    '/test-payment': {
      preLoaderRoute: typeof TestPaymentLazyImport
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      preLoaderRoute: typeof TransactionsLazyImport
      parentRoute: typeof rootRoute
    }
    '/transactions/$id': {
      preLoaderRoute: typeof TransactionsIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  LoginLazyRoute,
  RefundsLazyRoute,
  TestPaymentLazyRoute,
  TransactionsLazyRoute,
  TransactionsIdLazyRoute,
])

/* prettier-ignore-end */
