/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as OrdersImport } from './routes/orders'
import { Route as LoginImport } from './routes/login'
import { Route as FavoritesImport } from './routes/favorites'
import { Route as CheckoutImport } from './routes/checkout'
import { Route as CartImport } from './routes/cart'
import { Route as IndexImport } from './routes/index'
import { Route as SearchImport } from './routes/search'
import { Route as ShopShopSlugImport } from './routes/shop.$shopSlug'
import { Route as ProductProductIdImport } from './routes/product.$productId'
import { Route as CategoryCategorySlugImport } from './routes/category.$categorySlug'
import { Route as SellerDashboardImport } from './routes/seller/dashboard'
import { Route as SellerCreateShopImport } from './routes/seller/create-shop'
import { Route as SellerProductsNewImport } from './routes/seller/products.new'

// Create Virtual Filewave Routes

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const OrdersRoute = OrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesRoute = FavoritesImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutRoute = CheckoutImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const ShopShopSlugRoute = ShopShopSlugImport.update({
  id: '/shop/$shopSlug',
  path: '/shop/$shopSlug',
  getParentRoute: () => rootRoute,
} as any)

const ProductProductIdRoute = ProductProductIdImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRoute,
} as any)

const CategoryCategorySlugRoute = CategoryCategorySlugImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRoute,
} as any)

const SellerDashboardRoute = SellerDashboardImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const SellerCreateShopRoute = SellerCreateShopImport.update({
  id: '/seller/create-shop',
  path: '/seller/create-shop',
  getParentRoute: () => rootRoute,
} as any)

const SellerProductsNewRoute = SellerProductsNewImport.update({
  id: '/seller/products/new',
  path: '/seller/products/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutImport
      parentRoute: typeof rootRoute
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugImport
      parentRoute: typeof rootRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdImport
      parentRoute: typeof rootRoute
    }
    '/shop/$shopSlug': {
      id: '/shop/$shopSlug'
      path: '/shop/$shopSlug'
      fullPath: '/shop/$shopSlug'
      preLoaderRoute: typeof ShopShopSlugImport
      parentRoute: typeof rootRoute
    }
    '/seller/create-shop': {
      id: '/seller/create-shop'
      path: '/seller/create-shop'
      fullPath: '/seller/create-shop'
      preLoaderRoute: typeof SellerCreateShopImport
      parentRoute: typeof rootRoute
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardImport
      parentRoute: typeof rootRoute
    }
    '/seller/products/new': {
      id: '/seller/products/new'
      path: '/seller/products/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof SellerProductsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$shopSlug': typeof ShopShopSlugRoute
  '/seller/create-shop': typeof SellerCreateShopRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/products/new': typeof SellerProductsNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$shopSlug': typeof ShopShopSlugRoute
  '/seller/create-shop': typeof SellerCreateShopRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/products/new': typeof SellerProductsNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$shopSlug': typeof ShopShopSlugRoute
  '/seller/create-shop': typeof SellerCreateShopRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/products/new': typeof SellerProductsNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/orders'
    | '/register'
    | '/search'
    | '/category/$categorySlug'
    | '/product/$productId'
    | '/shop/$shopSlug'
    | '/seller/create-shop'
    | '/seller/dashboard'
    | '/seller/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/orders'
    | '/register'
    | '/search'
    | '/category/$categorySlug'
    | '/product/$productId'
    | '/shop/$shopSlug'
    | '/seller/create-shop'
    | '/seller/dashboard'
    | '/seller/products/new'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/orders'
    | '/register'
    | '/search'
    | '/category/$categorySlug'
    | '/product/$productId'
    | '/shop/$shopSlug'
    | '/seller/create-shop'
    | '/seller/dashboard'
    | '/seller/products/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ShopShopSlugRoute: typeof ShopShopSlugRoute
  SellerCreateShopRoute: typeof SellerCreateShopRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerProductsNewRoute: typeof SellerProductsNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ShopShopSlugRoute: ShopShopSlugRoute,
  SellerCreateShopRoute: SellerCreateShopRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerProductsNewRoute: SellerProductsNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */
