/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file will be auto-generated by the TanStack Router Vite plugin.
// Run `npm run dev` or `npm run build` to regenerate it.

import { Route as rootRoute } from './routes/__root'
import { Route as TrendingImport } from './routes/trending'
import { Route as SettingsImport } from './routes/settings'
import { Route as SearchImport } from './routes/search'
import { Route as LoginImport } from './routes/login'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as TopicsIndexImport } from './routes/topics.index'
import { Route as TopicsTopicImport } from './routes/topics.$topic'
import { Route as StoryStoryIdImport } from './routes/story.$storyId'

const TrendingRoute = TrendingImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TopicsIndexRoute = TopicsIndexImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRoute,
} as any)

const TopicsTopicRoute = TopicsTopicImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => rootRoute,
} as any)

const StoryStoryIdRoute = StoryStoryIdImport.update({
  id: '/story/$storyId',
  path: '/story/$storyId',
  getParentRoute: () => rootRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/topics/': typeof TopicsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/topics': typeof TopicsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/topics/': typeof TopicsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/search'
    | '/settings'
    | '/trending'
    | '/story/$storyId'
    | '/topics/$topic'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/search'
    | '/settings'
    | '/trending'
    | '/story/$storyId'
    | '/topics/$topic'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/search'
    | '/settings'
    | '/trending'
    | '/story/$storyId'
    | '/topics/$topic'
    | '/topics/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TrendingRoute: typeof TrendingRoute
  StoryStoryIdRoute: typeof StoryStoryIdRoute
  TopicsTopicRoute: typeof TopicsTopicRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TrendingRoute: TrendingRoute,
  StoryStoryIdRoute: StoryStoryIdRoute,
  TopicsTopicRoute: TopicsTopicRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingImport
      parentRoute: typeof rootRoute
    }
    '/story/$storyId': {
      id: '/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/story/$storyId'
      preLoaderRoute: typeof StoryStoryIdImport
      parentRoute: typeof rootRoute
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicImport
      parentRoute: typeof rootRoute
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics/'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}
