/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router'

// Import Routes
import { Route as rootRoute } from './routes/__root'
import { Route as SigningDeclinedRoute } from './routes/signing-declined'
import { Route as SigningCompleteRoute } from './routes/signing-complete'
import { Route as RegisterRoute } from './routes/register'
import { Route as LoginRoute } from './routes/login'
import { Route as AdminRoute } from './routes/admin'
import { Route as IndexRoute } from './routes/index'
import { Route as SignAccessTokenRoute } from './routes/sign/$accessToken'
import { Route as EnvelopesNewRoute } from './routes/envelopes/new'
import { Route as EnvelopesIndexRoute } from './routes/envelopes/index'
import { Route as EnvelopesEnvelopeIdRoute } from './routes/envelopes/$envelopeId'

// Create/Update Routes
const SigningDeclinedRouteWithChildren = SigningDeclinedRoute
const SigningCompleteRouteWithChildren = SigningCompleteRoute
const RegisterRouteWithChildren = RegisterRoute
const LoginRouteWithChildren = LoginRoute
const AdminRouteWithChildren = AdminRoute
const IndexRouteWithChildren = IndexRoute
const SignAccessTokenRouteWithChildren = SignAccessTokenRoute
const EnvelopesNewRouteWithChildren = EnvelopesNewRoute
const EnvelopesIndexRouteWithChildren = EnvelopesIndexRoute
const EnvelopesEnvelopeIdRouteWithChildren = EnvelopesEnvelopeIdRoute

// Create and export the route tree
export const routeTree = rootRoute.addChildren([
  IndexRouteWithChildren,
  LoginRouteWithChildren,
  RegisterRouteWithChildren,
  AdminRouteWithChildren,
  SigningCompleteRouteWithChildren,
  SigningDeclinedRouteWithChildren,
  SignAccessTokenRouteWithChildren,
  EnvelopesIndexRouteWithChildren,
  EnvelopesNewRouteWithChildren,
  EnvelopesEnvelopeIdRouteWithChildren,
])

/* prettier-ignore-end */
