/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelsAtmeRouteImport } from './routes/channels/@me'
import { Route as ChannelsRoomIdRouteImport } from './routes/channels/$roomId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsAtmeRoute = ChannelsAtmeRouteImport.update({
  id: '/@me',
  path: '/@me',
  getParentRoute: () => ChannelsRoute,
} as any)
const ChannelsRoomIdRoute = ChannelsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ChannelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/login': typeof LoginRoute
  '/channels/$roomId': typeof ChannelsRoomIdRoute
  '/channels/@me': typeof ChannelsAtmeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/login': typeof LoginRoute
  '/channels/$roomId': typeof ChannelsRoomIdRoute
  '/channels/@me': typeof ChannelsAtmeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/login': typeof LoginRoute
  '/channels/$roomId': typeof ChannelsRoomIdRoute
  '/channels/@me': typeof ChannelsAtmeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/login'
    | '/channels/$roomId'
    | '/channels/@me'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/channels' | '/login' | '/channels/$roomId' | '/channels/@me'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/login'
    | '/channels/$roomId'
    | '/channels/@me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/@me': {
      id: '/channels/@me'
      path: '/@me'
      fullPath: '/channels/@me'
      preLoaderRoute: typeof ChannelsAtmeRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/channels/$roomId': {
      id: '/channels/$roomId'
      path: '/$roomId'
      fullPath: '/channels/$roomId'
      preLoaderRoute: typeof ChannelsRoomIdRouteImport
      parentRoute: typeof ChannelsRoute
    }
  }
}

interface ChannelsRouteChildren {
  ChannelsRoomIdRoute: typeof ChannelsRoomIdRoute
  ChannelsAtmeRoute: typeof ChannelsAtmeRoute
}

const ChannelsRouteChildren: ChannelsRouteChildren = {
  ChannelsRoomIdRoute: ChannelsRoomIdRoute,
  ChannelsAtmeRoute: ChannelsAtmeRoute,
}

const ChannelsRouteWithChildren = ChannelsRoute._addFileChildren(
  ChannelsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
