/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as CartImport } from './routes/cart'
import { Route as IndexImport } from './routes/index'
import { Route as RestaurantDashboardImport } from './routes/restaurant-dashboard'
import { Route as DriverDashboardImport } from './routes/driver-dashboard'
import { Route as RestaurantRestaurantIdImport } from './routes/restaurant.$restaurantId'
import { Route as OrdersIndexImport } from './routes/orders.index'
import { Route as OrdersOrderIdImport } from './routes/orders.$orderId'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RestaurantDashboardRoute = RestaurantDashboardImport.update({
  id: '/restaurant-dashboard',
  path: '/restaurant-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DriverDashboardRoute = DriverDashboardImport.update({
  id: '/driver-dashboard',
  path: '/driver-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const RestaurantRestaurantIdRoute = RestaurantRestaurantIdImport.update({
  id: '/restaurant/$restaurantId',
  path: '/restaurant/$restaurantId',
  getParentRoute: () => rootRoute,
} as any)

const OrdersIndexRoute = OrdersIndexImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any)

const OrdersOrderIdRoute = OrdersOrderIdImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/restaurant-dashboard': {
      id: '/restaurant-dashboard'
      path: '/restaurant-dashboard'
      fullPath: '/restaurant-dashboard'
      preLoaderRoute: typeof RestaurantDashboardImport
      parentRoute: typeof rootRoute
    }
    '/driver-dashboard': {
      id: '/driver-dashboard'
      path: '/driver-dashboard'
      fullPath: '/driver-dashboard'
      preLoaderRoute: typeof DriverDashboardImport
      parentRoute: typeof rootRoute
    }
    '/restaurant/$restaurantId': {
      id: '/restaurant/$restaurantId'
      path: '/restaurant/$restaurantId'
      fullPath: '/restaurant/$restaurantId'
      preLoaderRoute: typeof RestaurantRestaurantIdImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexImport
      parentRoute: typeof rootRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRoute
  '/driver-dashboard': typeof DriverDashboardRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/orders': typeof OrdersIndexRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRoute
  '/driver-dashboard': typeof DriverDashboardRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/orders': typeof OrdersIndexRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRoute
  '/driver-dashboard': typeof DriverDashboardRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/orders': typeof OrdersIndexRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/login'
    | '/register'
    | '/restaurant-dashboard'
    | '/driver-dashboard'
    | '/restaurant/$restaurantId'
    | '/orders'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/login'
    | '/register'
    | '/restaurant-dashboard'
    | '/driver-dashboard'
    | '/restaurant/$restaurantId'
    | '/orders'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/login'
    | '/register'
    | '/restaurant-dashboard'
    | '/driver-dashboard'
    | '/restaurant/$restaurantId'
    | '/orders'
    | '/orders/$orderId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RestaurantDashboardRoute: typeof RestaurantDashboardRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  RestaurantRestaurantIdRoute: typeof RestaurantRestaurantIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RestaurantDashboardRoute: RestaurantDashboardRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  RestaurantRestaurantIdRoute: RestaurantRestaurantIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
