/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BecomeHostRouteImport } from './routes/become-host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as HostReservationsRouteImport } from './routes/host/reservations'
import { Route as HostListingsRouteImport } from './routes/host/listings'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as HostListingsNewRouteImport } from './routes/host/listings.new'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeHostRoute = BecomeHostRouteImport.update({
  id: '/become-host',
  path: '/become-host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostReservationsRoute = HostReservationsRouteImport.update({
  id: '/host/reservations',
  path: '/host/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const HostListingsRoute = HostListingsRouteImport.update({
  id: '/host/listings',
  path: '/host/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostListingsNewRoute = HostListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HostListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/booking/$id': typeof BookingIdRoute
  '/host/listings': typeof HostListingsRouteWithChildren
  '/host/reservations': typeof HostReservationsRoute
  '/listing/$id': typeof ListingIdRoute
  '/host/listings/new': typeof HostListingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/booking/$id': typeof BookingIdRoute
  '/host/listings': typeof HostListingsRouteWithChildren
  '/host/reservations': typeof HostReservationsRoute
  '/listing/$id': typeof ListingIdRoute
  '/host/listings/new': typeof HostListingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/booking/$id': typeof BookingIdRoute
  '/host/listings': typeof HostListingsRouteWithChildren
  '/host/reservations': typeof HostReservationsRoute
  '/listing/$id': typeof ListingIdRoute
  '/host/listings/new': typeof HostListingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-host'
    | '/login'
    | '/messages'
    | '/register'
    | '/search'
    | '/trips'
    | '/booking/$id'
    | '/host/listings'
    | '/host/reservations'
    | '/listing/$id'
    | '/host/listings/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-host'
    | '/login'
    | '/messages'
    | '/register'
    | '/search'
    | '/trips'
    | '/booking/$id'
    | '/host/listings'
    | '/host/reservations'
    | '/listing/$id'
    | '/host/listings/new'
  id:
    | '__root__'
    | '/'
    | '/become-host'
    | '/login'
    | '/messages'
    | '/register'
    | '/search'
    | '/trips'
    | '/booking/$id'
    | '/host/listings'
    | '/host/reservations'
    | '/listing/$id'
    | '/host/listings/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeHostRoute: typeof BecomeHostRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  TripsRoute: typeof TripsRoute
  BookingIdRoute: typeof BookingIdRoute
  HostListingsRoute: typeof HostListingsRouteWithChildren
  HostReservationsRoute: typeof HostReservationsRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-host': {
      id: '/become-host'
      path: '/become-host'
      fullPath: '/become-host'
      preLoaderRoute: typeof BecomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/reservations': {
      id: '/host/reservations'
      path: '/host/reservations'
      fullPath: '/host/reservations'
      preLoaderRoute: typeof HostReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/listings': {
      id: '/host/listings'
      path: '/host/listings'
      fullPath: '/host/listings'
      preLoaderRoute: typeof HostListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/listings/new': {
      id: '/host/listings/new'
      path: '/new'
      fullPath: '/host/listings/new'
      preLoaderRoute: typeof HostListingsNewRouteImport
      parentRoute: typeof HostListingsRoute
    }
  }
}

interface HostListingsRouteChildren {
  HostListingsNewRoute: typeof HostListingsNewRoute
}

const HostListingsRouteChildren: HostListingsRouteChildren = {
  HostListingsNewRoute: HostListingsNewRoute,
}

const HostListingsRouteWithChildren = HostListingsRoute._addFileChildren(
  HostListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeHostRoute: BecomeHostRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  TripsRoute: TripsRoute,
  BookingIdRoute: BookingIdRoute,
  HostListingsRoute: HostListingsRouteWithChildren,
  HostReservationsRoute: HostReservationsRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
