/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadImport } from './routes/upload'
import { Route as StatsImport } from './routes/stats'
import { Route as SegmentsImport } from './routes/segments'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as ExploreImport } from './routes/explore'
import { Route as IndexImport } from './routes/index'
import { Route as SegmentIdImport } from './routes/segment.$id'
import { Route as ProfileIdImport } from './routes/profile.$id'
import { Route as ActivityIdImport } from './routes/activity.$id'
import { Route as ProfileIdFollowingImport } from './routes/profile.$id.following'
import { Route as ProfileIdFollowersImport } from './routes/profile.$id.followers'

// Create Virtual Routes

// Create/Update Routes

const UploadRoute = UploadImport.update({
  path: '/upload',
  getParentRoute: () => rootRoute,
} as any)

const StatsRoute = StatsImport.update({
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any)

const SegmentsRoute = SegmentsImport.update({
  path: '/segments',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ExploreRoute = ExploreImport.update({
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SegmentIdRoute = SegmentIdImport.update({
  path: '/segment/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIdRoute = ProfileIdImport.update({
  path: '/profile/$id',
  getParentRoute: () => rootRoute,
} as any)

const ActivityIdRoute = ActivityIdImport.update({
  path: '/activity/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIdFollowingRoute = ProfileIdFollowingImport.update({
  path: '/profile/$id/following',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIdFollowersRoute = ProfileIdFollowersImport.update({
  path: '/profile/$id/followers',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/explore': {
      preLoaderRoute: typeof ExploreImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/segments': {
      preLoaderRoute: typeof SegmentsImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      preLoaderRoute: typeof StatsImport
      parentRoute: typeof rootRoute
    }
    '/upload': {
      preLoaderRoute: typeof UploadImport
      parentRoute: typeof rootRoute
    }
    '/activity/$id': {
      preLoaderRoute: typeof ActivityIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id': {
      preLoaderRoute: typeof ProfileIdImport
      parentRoute: typeof rootRoute
    }
    '/segment/$id': {
      preLoaderRoute: typeof SegmentIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id/followers': {
      preLoaderRoute: typeof ProfileIdFollowersImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id/following': {
      preLoaderRoute: typeof ProfileIdFollowingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ExploreRoute,
  LoginRoute,
  RegisterRoute,
  SegmentsRoute,
  StatsRoute,
  UploadRoute,
  ActivityIdRoute,
  ProfileIdRoute,
  SegmentIdRoute,
  ProfileIdFollowersRoute,
  ProfileIdFollowingRoute,
])

/* prettier-ignore-end */
