/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Children

const TrendingLazyImport = createFileRoute('/trending')()
const RegisterLazyImport = createFileRoute('/register')()
const LoginLazyImport = createFileRoute('/login')()
const LibraryLazyImport = createFileRoute('/library')()
const ExportLazyImport = createFileRoute('/export')()
const IndexLazyImport = createFileRoute('/')()
const BooksBookIdLazyImport = createFileRoute('/books/$bookId')()

// Create/Update Routes

const TrendingLazyRoute = TrendingLazyImport.update({
  path: '/trending',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/trending').then((d) => d.Route))

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login').then((d) => d.Route))

const LibraryLazyRoute = LibraryLazyImport.update({
  path: '/library',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/library').then((d) => d.Route))

const ExportLazyRoute = ExportLazyImport.update({
  path: '/export',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/export').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

const BooksBookIdLazyRoute = BooksBookIdLazyImport.update({
  path: '/books/$bookId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/books.$bookId').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportLazyImport
      parentRoute: typeof rootRoute
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingLazyImport
      parentRoute: typeof rootRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ExportLazyRoute,
  LibraryLazyRoute,
  LoginLazyRoute,
  RegisterLazyRoute,
  TrendingLazyRoute,
  BooksBookIdLazyRoute,
})

/* prettier-ignore-end */
