/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WebhooksImport } from './routes/webhooks'
import { Route as PaymentsImport } from './routes/payments'
import { Route as CustomersImport } from './routes/customers'
import { Route as CheckoutImport } from './routes/checkout'
import { Route as BalanceImport } from './routes/balance'
import { Route as IndexImport } from './routes/index'

// Create Virtual Childed Route Ids

// Create/Update Routes

const WebhooksRoute = WebhooksImport.update({
  path: '/webhooks',
  getParentRoute: () => rootRoute,
} as any)

const PaymentsRoute = PaymentsImport.update({
  path: '/payments',
  getParentRoute: () => rootRoute,
} as any)

const CustomersRoute = CustomersImport.update({
  path: '/customers',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutRoute = CheckoutImport.update({
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any)

const BalanceRoute = BalanceImport.update({
  path: '/balance',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceImport
      parentRoute: typeof rootRoute
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutImport
      parentRoute: typeof rootRoute
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersImport
      parentRoute: typeof rootRoute
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsImport
      parentRoute: typeof rootRoute
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/checkout': typeof CheckoutRoute
  '/customers': typeof CustomersRoute
  '/payments': typeof PaymentsRoute
  '/webhooks': typeof WebhooksRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/checkout': typeof CheckoutRoute
  '/customers': typeof CustomersRoute
  '/payments': typeof PaymentsRoute
  '/webhooks': typeof WebhooksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/checkout': typeof CheckoutRoute
  '/customers': typeof CustomersRoute
  '/payments': typeof PaymentsRoute
  '/webhooks': typeof WebhooksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance'
    | '/checkout'
    | '/customers'
    | '/payments'
    | '/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/balance' | '/checkout' | '/customers' | '/payments' | '/webhooks'
  id:
    | '__root__'
    | '/'
    | '/balance'
    | '/checkout'
    | '/customers'
    | '/payments'
    | '/webhooks'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalanceRoute: typeof BalanceRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomersRoute: typeof CustomersRoute
  PaymentsRoute: typeof PaymentsRoute
  WebhooksRoute: typeof WebhooksRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalanceRoute: BalanceRoute,
  CheckoutRoute: CheckoutRoute,
  CustomersRoute: CustomersRoute,
  PaymentsRoute: PaymentsRoute,
  WebhooksRoute: WebhooksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */
