/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const LoginLazyImport = createFileRoute('/login')()
const DeveloperLazyImport = createFileRoute('/developer')()
const CategoriesLazyImport = createFileRoute('/categories')()
const IndexLazyImport = createFileRoute('/')()
const SearchLazyImport = createFileRoute('/search')()
const CategorySlugLazyImport = createFileRoute('/category/$slug')()
const AppIdLazyImport = createFileRoute('/app/$id')()
const DeveloperAppIdLazyImport = createFileRoute('/developer/app/$id')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login').then((d) => d.Route))

const DeveloperLazyRoute = DeveloperLazyImport.update({
  path: '/developer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/developer').then((d) => d.Route))

const CategoriesLazyRoute = CategoriesLazyImport.update({
  path: '/categories',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/categories').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

const SearchLazyRoute = SearchLazyImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/search').then((d) => d.Route))

const CategorySlugLazyRoute = CategorySlugLazyImport.update({
  path: '/category/$slug',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/category.$slug').then((d) => d.Route))

const AppIdLazyRoute = AppIdLazyImport.update({
  path: '/app/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/app.$id').then((d) => d.Route))

const DeveloperAppIdLazyRoute = DeveloperAppIdLazyImport.update({
  path: '/developer/app/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/developer.app.$id').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/categories': {
      preLoaderRoute: typeof CategoriesLazyImport
      parentRoute: typeof rootRoute
    }
    '/developer': {
      preLoaderRoute: typeof DeveloperLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      preLoaderRoute: typeof SearchLazyImport
      parentRoute: typeof rootRoute
    }
    '/app/$id': {
      preLoaderRoute: typeof AppIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/category/$slug': {
      preLoaderRoute: typeof CategorySlugLazyImport
      parentRoute: typeof rootRoute
    }
    '/developer/app/$id': {
      preLoaderRoute: typeof DeveloperAppIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CategoriesLazyRoute,
  DeveloperLazyRoute,
  LoginLazyRoute,
  RegisterLazyRoute,
  SearchLazyRoute,
  AppIdLazyRoute,
  CategorySlugLazyRoute,
  DeveloperAppIdLazyRoute,
])

/* prettier-ignore-end */
