/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeSymbolRouteImport } from './routes/trade.$symbol'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeSymbolRoute = TradeSymbolRouteImport.update({
  id: '/trade/$symbol',
  path: '/trade/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/trade/$symbol': typeof TradeSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/trade/$symbol': typeof TradeSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/trade/$symbol': typeof TradeSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/orders' | '/portfolio' | '/register' | '/trade/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/orders' | '/portfolio' | '/register' | '/trade/$symbol'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/orders'
    | '/portfolio'
    | '/register'
    | '/trade/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PortfolioRoute: typeof PortfolioRoute
  RegisterRoute: typeof RegisterRoute
  TradeSymbolRoute: typeof TradeSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$symbol': {
      id: '/trade/$symbol'
      path: '/trade/$symbol'
      fullPath: '/trade/$symbol'
      preLoaderRoute: typeof TradeSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PortfolioRoute: PortfolioRoute,
  RegisterRoute: RegisterRoute,
  TradeSymbolRoute: TradeSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
