import { StrictMode, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { useAuthStore } from './stores/authStore';
import './index.css';

// Import the generated route tree
import { routeTree } from './routeTree.gen';

/**
 * Create the TanStack Router instance with the generated route tree.
 * Route tree is auto-generated by the TanStack Router Vite plugin.
 */
const router = createRouter({ routeTree });

/**
 * Register router type for TypeScript type safety.
 * Enables proper typing for navigation and route params.
 */
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

/**
 * Root application component.
 * Checks authentication on mount and provides the router.
 */
function App() {
  const { checkAuth } = useAuthStore();

  useEffect(() => {
    checkAuth();
  }, [checkAuth]);

  return <RouterProvider router={router} />;
}

/**
 * Mount the React application to the DOM.
 * Uses StrictMode for development warnings and checks.
 */
createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
