/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const MeetingTypesLazyImport = createFileRoute('/meeting-types')()
const LoginLazyImport = createFileRoute('/login')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const BookingsLazyImport = createFileRoute('/bookings')()
const AvailabilityLazyImport = createFileRoute('/availability')()
const AdminLazyImport = createFileRoute('/admin')()
const IndexLazyImport = createFileRoute('/')()
const BookingsBookingIdLazyImport = createFileRoute('/bookings/$bookingId')()
const BookMeetingTypeIdLazyImport = createFileRoute('/book/$meetingTypeId')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register').then((d) => d.Route))

const MeetingTypesLazyRoute = MeetingTypesLazyImport.update({
  path: '/meeting-types',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/meeting-types').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard').then((d) => d.Route))

const BookingsLazyRoute = BookingsLazyImport.update({
  path: '/bookings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bookings').then((d) => d.Route))

const AvailabilityLazyRoute = AvailabilityLazyImport.update({
  path: '/availability',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/availability').then((d) => d.Route))

const AdminLazyRoute = AdminLazyImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

const BookingsBookingIdLazyRoute = BookingsBookingIdLazyImport.update({
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bookings.$bookingId').then((d) => d.Route))

const BookMeetingTypeIdLazyRoute = BookMeetingTypeIdLazyImport.update({
  path: '/book/$meetingTypeId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/book.$meetingTypeId').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyImport
      parentRoute: typeof rootRoute
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityLazyImport
      parentRoute: typeof rootRoute
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/meeting-types': {
      id: '/meeting-types'
      path: '/meeting-types'
      fullPath: '/meeting-types'
      preLoaderRoute: typeof MeetingTypesLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/book/$meetingTypeId': {
      id: '/book/$meetingTypeId'
      path: '/book/$meetingTypeId'
      fullPath: '/book/$meetingTypeId'
      preLoaderRoute: typeof BookMeetingTypeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRoute
  '/availability': typeof AvailabilityLazyRoute
  '/bookings': typeof BookingsLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/login': typeof LoginLazyRoute
  '/meeting-types': typeof MeetingTypesLazyRoute
  '/register': typeof RegisterLazyRoute
  '/book/$meetingTypeId': typeof BookMeetingTypeIdLazyRoute
  '/bookings/$bookingId': typeof BookingsBookingIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRoute
  '/availability': typeof AvailabilityLazyRoute
  '/bookings': typeof BookingsLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/login': typeof LoginLazyRoute
  '/meeting-types': typeof MeetingTypesLazyRoute
  '/register': typeof RegisterLazyRoute
  '/book/$meetingTypeId': typeof BookMeetingTypeIdLazyRoute
  '/bookings/$bookingId': typeof BookingsBookingIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRoute
  '/availability': typeof AvailabilityLazyRoute
  '/bookings': typeof BookingsLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/login': typeof LoginLazyRoute
  '/meeting-types': typeof MeetingTypesLazyRoute
  '/register': typeof RegisterLazyRoute
  '/book/$meetingTypeId': typeof BookMeetingTypeIdLazyRoute
  '/bookings/$bookingId': typeof BookingsBookingIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/availability'
    | '/bookings'
    | '/dashboard'
    | '/login'
    | '/meeting-types'
    | '/register'
    | '/book/$meetingTypeId'
    | '/bookings/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/availability'
    | '/bookings'
    | '/dashboard'
    | '/login'
    | '/meeting-types'
    | '/register'
    | '/book/$meetingTypeId'
    | '/bookings/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/availability'
    | '/bookings'
    | '/dashboard'
    | '/login'
    | '/meeting-types'
    | '/register'
    | '/book/$meetingTypeId'
    | '/bookings/$bookingId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminLazyRoute: typeof AdminLazyRoute
  AvailabilityLazyRoute: typeof AvailabilityLazyRoute
  BookingsLazyRoute: typeof BookingsLazyRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  MeetingTypesLazyRoute: typeof MeetingTypesLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  BookMeetingTypeIdLazyRoute: typeof BookMeetingTypeIdLazyRoute
  BookingsBookingIdLazyRoute: typeof BookingsBookingIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminLazyRoute: AdminLazyRoute,
  AvailabilityLazyRoute: AvailabilityLazyRoute,
  BookingsLazyRoute: BookingsLazyRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  MeetingTypesLazyRoute: MeetingTypesLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  BookMeetingTypeIdLazyRoute: BookMeetingTypeIdLazyRoute,
  BookingsBookingIdLazyRoute: BookingsBookingIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */
