/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaceSpaceKeyRouteImport } from './routes/space.$spaceKey'
import { Route as SpaceSpaceKeyPageSlugRouteImport } from './routes/space.$spaceKey.page.$slug'
import { Route as SpaceSpaceKeyPageSlugEditRouteImport } from './routes/space.$spaceKey.page.$slug.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSpaceKeyRoute = SpaceSpaceKeyRouteImport.update({
  id: '/space/$spaceKey',
  path: '/space/$spaceKey',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSpaceKeyPageSlugRoute = SpaceSpaceKeyPageSlugRouteImport.update({
  id: '/page/$slug',
  path: '/page/$slug',
  getParentRoute: () => SpaceSpaceKeyRoute,
} as any)
const SpaceSpaceKeyPageSlugEditRoute =
  SpaceSpaceKeyPageSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => SpaceSpaceKeyPageSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/space/$spaceKey': typeof SpaceSpaceKeyRouteWithChildren
  '/space/$spaceKey/page/$slug': typeof SpaceSpaceKeyPageSlugRouteWithChildren
  '/space/$spaceKey/page/$slug/edit': typeof SpaceSpaceKeyPageSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/space/$spaceKey': typeof SpaceSpaceKeyRouteWithChildren
  '/space/$spaceKey/page/$slug': typeof SpaceSpaceKeyPageSlugRouteWithChildren
  '/space/$spaceKey/page/$slug/edit': typeof SpaceSpaceKeyPageSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/space/$spaceKey': typeof SpaceSpaceKeyRouteWithChildren
  '/space/$spaceKey/page/$slug': typeof SpaceSpaceKeyPageSlugRouteWithChildren
  '/space/$spaceKey/page/$slug/edit': typeof SpaceSpaceKeyPageSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/space/$spaceKey'
    | '/space/$spaceKey/page/$slug'
    | '/space/$spaceKey/page/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/space/$spaceKey'
    | '/space/$spaceKey/page/$slug'
    | '/space/$spaceKey/page/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/space/$spaceKey'
    | '/space/$spaceKey/page/$slug'
    | '/space/$spaceKey/page/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SpaceSpaceKeyRoute: typeof SpaceSpaceKeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/$spaceKey': {
      id: '/space/$spaceKey'
      path: '/space/$spaceKey'
      fullPath: '/space/$spaceKey'
      preLoaderRoute: typeof SpaceSpaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/$spaceKey/page/$slug': {
      id: '/space/$spaceKey/page/$slug'
      path: '/page/$slug'
      fullPath: '/space/$spaceKey/page/$slug'
      preLoaderRoute: typeof SpaceSpaceKeyPageSlugRouteImport
      parentRoute: typeof SpaceSpaceKeyRoute
    }
    '/space/$spaceKey/page/$slug/edit': {
      id: '/space/$spaceKey/page/$slug/edit'
      path: '/edit'
      fullPath: '/space/$spaceKey/page/$slug/edit'
      preLoaderRoute: typeof SpaceSpaceKeyPageSlugEditRouteImport
      parentRoute: typeof SpaceSpaceKeyPageSlugRoute
    }
  }
}

interface SpaceSpaceKeyPageSlugRouteChildren {
  SpaceSpaceKeyPageSlugEditRoute: typeof SpaceSpaceKeyPageSlugEditRoute
}

const SpaceSpaceKeyPageSlugRouteChildren: SpaceSpaceKeyPageSlugRouteChildren = {
  SpaceSpaceKeyPageSlugEditRoute: SpaceSpaceKeyPageSlugEditRoute,
}

const SpaceSpaceKeyPageSlugRouteWithChildren =
  SpaceSpaceKeyPageSlugRoute._addFileChildren(
    SpaceSpaceKeyPageSlugRouteChildren,
  )

interface SpaceSpaceKeyRouteChildren {
  SpaceSpaceKeyPageSlugRoute: typeof SpaceSpaceKeyPageSlugRouteWithChildren
}

const SpaceSpaceKeyRouteChildren: SpaceSpaceKeyRouteChildren = {
  SpaceSpaceKeyPageSlugRoute: SpaceSpaceKeyPageSlugRouteWithChildren,
}

const SpaceSpaceKeyRouteWithChildren = SpaceSpaceKeyRoute._addFileChildren(
  SpaceSpaceKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SpaceSpaceKeyRoute: SpaceSpaceKeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
