/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as WorkspaceSelectImport } from './routes/workspace-select'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as WorkspaceWorkspaceIdImport } from './routes/workspace/$workspaceId'
import { Route as WorkspaceWorkspaceIdIndexImport } from './routes/workspace/$workspaceId.index'
import { Route as WorkspaceWorkspaceIdChannelChannelIdImport } from './routes/workspace/$workspaceId/channel/$channelId'

const WorkspaceSelectRoute = WorkspaceSelectImport.update({
  path: '/workspace-select',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdImport.update({
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceWorkspaceIdIndexRoute = WorkspaceWorkspaceIdIndexImport.update({
  path: '/',
  getParentRoute: () => WorkspaceWorkspaceIdRoute,
} as any)

const WorkspaceWorkspaceIdChannelChannelIdRoute =
  WorkspaceWorkspaceIdChannelChannelIdImport.update({
    path: '/channel/$channelId',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace-select': typeof WorkspaceSelectRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/channel/$channelId': typeof WorkspaceWorkspaceIdChannelChannelIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace-select': typeof WorkspaceSelectRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/channel/$channelId': typeof WorkspaceWorkspaceIdChannelChannelIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace-select': typeof WorkspaceSelectRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/channel/$channelId': typeof WorkspaceWorkspaceIdChannelChannelIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspace-select'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workspace-select'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/workspace-select'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/channel/$channelId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WorkspaceSelectRoute: typeof WorkspaceSelectRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WorkspaceSelectRoute: WorkspaceSelectRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

interface WorkspaceWorkspaceIdRouteChildren {
  WorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceIdIndexRoute
  WorkspaceWorkspaceIdChannelChannelIdRoute: typeof WorkspaceWorkspaceIdChannelChannelIdRoute
}

const WorkspaceWorkspaceIdRouteChildren: WorkspaceWorkspaceIdRouteChildren = {
  WorkspaceWorkspaceIdIndexRoute: WorkspaceWorkspaceIdIndexRoute,
  WorkspaceWorkspaceIdChannelChannelIdRoute:
    WorkspaceWorkspaceIdChannelChannelIdRoute,
}

const WorkspaceWorkspaceIdRouteWithChildren =
  WorkspaceWorkspaceIdRoute._addFileChildren(WorkspaceWorkspaceIdRouteChildren)

/* prettier-ignore-end */
