/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceSelectRouteImport } from './routes/workspace-select'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace/$workspaceId'
import { Route as WorkspaceWorkspaceIdIndexRouteImport } from './routes/workspace/$workspaceId.index'
import { Route as WorkspaceWorkspaceIdChannelChannelIdRouteImport } from './routes/workspace/$workspaceId/channel/$channelId'

const WorkspaceSelectRoute = WorkspaceSelectRouteImport.update({
  id: '/workspace-select',
  path: '/workspace-select',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdIndexRoute =
  WorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdChannelChannelIdRoute =
  WorkspaceWorkspaceIdChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace-select': typeof WorkspaceSelectRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/channel/$channelId': typeof WorkspaceWorkspaceIdChannelChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace-select': typeof WorkspaceSelectRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/channel/$channelId': typeof WorkspaceWorkspaceIdChannelChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace-select': typeof WorkspaceSelectRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/channel/$channelId': typeof WorkspaceWorkspaceIdChannelChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspace-select'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workspace-select'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/workspace-select'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/channel/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WorkspaceSelectRoute: typeof WorkspaceSelectRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace-select': {
      id: '/workspace-select'
      path: '/workspace-select'
      fullPath: '/workspace-select'
      preLoaderRoute: typeof WorkspaceSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/': {
      id: '/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/channel/$channelId': {
      id: '/workspace/$workspaceId/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/workspace/$workspaceId/channel/$channelId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdChannelChannelIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
  }
}

interface WorkspaceWorkspaceIdRouteChildren {
  WorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceIdIndexRoute
  WorkspaceWorkspaceIdChannelChannelIdRoute: typeof WorkspaceWorkspaceIdChannelChannelIdRoute
}

const WorkspaceWorkspaceIdRouteChildren: WorkspaceWorkspaceIdRouteChildren = {
  WorkspaceWorkspaceIdIndexRoute: WorkspaceWorkspaceIdIndexRoute,
  WorkspaceWorkspaceIdChannelChannelIdRoute:
    WorkspaceWorkspaceIdChannelChannelIdRoute,
}

const WorkspaceWorkspaceIdRouteWithChildren =
  WorkspaceWorkspaceIdRoute._addFileChildren(WorkspaceWorkspaceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WorkspaceSelectRoute: WorkspaceSelectRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
