CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(30) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(100),
  avatar_url TEXT,
  role VARCHAR(20) DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  description TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS org_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  role VARCHAR(20) DEFAULT 'member',
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(org_id, user_id)
);

CREATE TABLE IF NOT EXISTS teams (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  is_private BOOLEAN DEFAULT false,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS team_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id UUID REFERENCES teams(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  role VARCHAR(20) DEFAULT 'member',
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(team_id, user_id)
);

CREATE TABLE IF NOT EXISTS channels (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id UUID REFERENCES teams(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  is_private BOOLEAN DEFAULT false,
  created_by UUID REFERENCES users(id),
  -- Highest event sequence number issued in this channel; see next_channel_seq()
  last_seq BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS channel_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID REFERENCES channels(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  last_read_at TIMESTAMPTZ DEFAULT NOW(),
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(channel_id, user_id)
);

CREATE TABLE IF NOT EXISTS messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID REFERENCES channels(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES users(id) NOT NULL,
  parent_message_id UUID REFERENCES messages(id),
  content TEXT NOT NULL,
  is_edited BOOLEAN DEFAULT false,
  -- Position in the channel's event stream, assigned by trg_messages_before_insert
  seq BIGINT NOT NULL,
  -- Generated by the sender for each message; a retried send returns the original row
  client_message_id UUID,
  -- Soft delete: the row stays so thread replies keep their root
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS message_reactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID REFERENCES messages(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES users(id) NOT NULL,
  emoji VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(message_id, user_id, emoji)
);

CREATE TABLE IF NOT EXISTS files (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID REFERENCES messages(id) ON DELETE CASCADE,
  channel_id UUID REFERENCES channels(id) NOT NULL,
  user_id UUID REFERENCES users(id) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(100),
  size_bytes BIGINT,
  storage_path TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ordered log of everything a channel's viewers must see: new, edited and deleted messages and
-- reaction changes. Rows are written in the same transaction as the change they describe, so the
-- log is the source of truth for real-time delivery; Redis pub/sub only signals that a new row
-- exists. Reconnecting clients replay rows after their last seen seq (SSE Last-Event-ID).
CREATE TABLE IF NOT EXISTS channel_events (
  channel_id UUID REFERENCES channels(id) ON DELETE CASCADE NOT NULL,
  seq BIGINT NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (channel_id, seq)
);

-- Databases created before sequencing existed get the new columns here (no-ops on fresh ones).
ALTER TABLE channels ADD COLUMN IF NOT EXISTS last_seq BIGINT NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS seq BIGINT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS client_message_id UUID;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- Number pre-existing messages per channel in creation order, continuing after the channel's
-- counter, then move each counter up to its highest number. Both statements touch nothing once
-- every message has a seq.
WITH numbered AS (
  SELECT m.id,
         c.last_seq + ROW_NUMBER() OVER (PARTITION BY m.channel_id ORDER BY m.created_at, m.id) AS seq
  FROM messages m
  JOIN channels c ON c.id = m.channel_id
  WHERE m.seq IS NULL
)
UPDATE messages m SET seq = numbered.seq FROM numbered WHERE m.id = numbered.id;

UPDATE channels c SET last_seq = s.max_seq
FROM (SELECT channel_id, MAX(seq) AS max_seq FROM messages GROUP BY channel_id) s
WHERE c.id = s.channel_id AND c.last_seq < s.max_seq;

ALTER TABLE messages ALTER COLUMN seq SET NOT NULL;

-- Issues the next sequence number for a channel. The UPDATE holds the channel's row lock until
-- the calling transaction ends, which gives two guarantees that a SEQUENCE would not: numbers
-- are gapless (a rollback hands the number back) and number N is committed before N + 1 is
-- issued, so a reader that sees seq 7 can rely on seq 6 already being visible. The price is
-- that writes to one channel are serialized, which is fine at chat message rates.
CREATE OR REPLACE FUNCTION next_channel_seq(p_channel_id UUID) RETURNS BIGINT AS $$
  UPDATE channels SET last_seq = last_seq + 1 WHERE id = p_channel_id RETURNING last_seq;
$$ LANGUAGE sql;

-- Runs for every message insert, from any code path (API, seed, psql): a reply must hang off a
-- top-level message in the same channel (threads are one level deep), and the message takes
-- the next sequence number in its channel.
CREATE OR REPLACE FUNCTION messages_before_insert() RETURNS trigger AS $$
BEGIN
  IF NEW.parent_message_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM messages p
    WHERE p.id = NEW.parent_message_id
      AND p.channel_id = NEW.channel_id
      AND p.parent_message_id IS NULL
  ) THEN
    RAISE EXCEPTION 'thread replies must reference a top-level message in the same channel'
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.seq IS NULL THEN
    NEW.seq := next_channel_seq(NEW.channel_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_messages_before_insert
  BEFORE INSERT ON messages
  FOR EACH ROW EXECUTE FUNCTION messages_before_insert();

-- History pages and replay read by (channel_id, seq); created_at no longer orders anything.
DROP INDEX IF EXISTS idx_messages_channel;
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_channel_seq ON messages(channel_id, seq);
CREATE INDEX IF NOT EXISTS idx_messages_channel_top
  ON messages(channel_id, seq DESC) WHERE parent_message_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_client_id
  ON messages(user_id, client_message_id) WHERE client_message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_messages_parent ON messages(parent_message_id);
CREATE INDEX IF NOT EXISTS idx_reactions_message ON message_reactions(message_id);
CREATE INDEX IF NOT EXISTS idx_files_channel ON files(channel_id);
CREATE INDEX IF NOT EXISTS idx_files_message ON files(message_id);
CREATE INDEX IF NOT EXISTS idx_org_members ON org_members(user_id);
CREATE INDEX IF NOT EXISTS idx_team_members ON team_members(user_id);
CREATE INDEX IF NOT EXISTS idx_channel_members ON channel_members(user_id);
