/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes to this file.
// This file will be regenerated when running `npm run dev` with the TanStack Router plugin.

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

// Import Routes
import { Route as RootRoute } from './routes/__root'
import { Route as TestRoute } from './routes/test'
import { Route as KeysRoute } from './routes/keys'
import { Route as ClusterRoute } from './routes/cluster'
import { Route as IndexRoute } from './routes/index'

// Create/Update Routes
const TestRouteWithChildren = TestRoute
const KeysRouteWithChildren = KeysRoute
const ClusterRouteWithChildren = ClusterRoute
const IndexRouteWithChildren = IndexRoute

// Create Route Tree
export const routeTree = RootRoute.addChildren({
  IndexRoute: IndexRouteWithChildren,
  TestRoute: TestRouteWithChildren,
  KeysRoute: KeysRouteWithChildren,
  ClusterRoute: ClusterRouteWithChildren,
})
