/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrgRouteImport } from './routes/org'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgOrgIdRouteImport } from './routes/org.$orgId'
import { Route as OrgOrgIdTeamTeamIdRouteImport } from './routes/org.$orgId.team.$teamId'
import { Route as OrgOrgIdTeamTeamIdChannelChannelIdRouteImport } from './routes/org.$orgId.team.$teamId.channel.$channelId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdRoute = OrgOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrgIdTeamTeamIdRoute = OrgOrgIdTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdTeamTeamIdChannelChannelIdRoute =
  OrgOrgIdTeamTeamIdChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => OrgOrgIdTeamTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/org': typeof OrgRouteWithChildren
  '/register': typeof RegisterRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/org/$orgId/team/$teamId': typeof OrgOrgIdTeamTeamIdRouteWithChildren
  '/org/$orgId/team/$teamId/channel/$channelId': typeof OrgOrgIdTeamTeamIdChannelChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/org': typeof OrgRouteWithChildren
  '/register': typeof RegisterRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/org/$orgId/team/$teamId': typeof OrgOrgIdTeamTeamIdRouteWithChildren
  '/org/$orgId/team/$teamId/channel/$channelId': typeof OrgOrgIdTeamTeamIdChannelChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/org': typeof OrgRouteWithChildren
  '/register': typeof RegisterRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/org/$orgId/team/$teamId': typeof OrgOrgIdTeamTeamIdRouteWithChildren
  '/org/$orgId/team/$teamId/channel/$channelId': typeof OrgOrgIdTeamTeamIdChannelChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/org'
    | '/register'
    | '/org/$orgId'
    | '/org/$orgId/team/$teamId'
    | '/org/$orgId/team/$teamId/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/org'
    | '/register'
    | '/org/$orgId'
    | '/org/$orgId/team/$teamId'
    | '/org/$orgId/team/$teamId/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/org'
    | '/register'
    | '/org/$orgId'
    | '/org/$orgId/team/$teamId'
    | '/org/$orgId/team/$teamId/channel/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrgRoute: typeof OrgRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId': {
      id: '/org/$orgId'
      path: '/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof OrgOrgIdRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/$orgId/team/$teamId': {
      id: '/org/$orgId/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/org/$orgId/team/$teamId'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/team/$teamId/channel/$channelId': {
      id: '/org/$orgId/team/$teamId/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/org/$orgId/team/$teamId/channel/$channelId'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdChannelChannelIdRouteImport
      parentRoute: typeof OrgOrgIdTeamTeamIdRoute
    }
  }
}

interface OrgOrgIdTeamTeamIdRouteChildren {
  OrgOrgIdTeamTeamIdChannelChannelIdRoute: typeof OrgOrgIdTeamTeamIdChannelChannelIdRoute
}

const OrgOrgIdTeamTeamIdRouteChildren: OrgOrgIdTeamTeamIdRouteChildren = {
  OrgOrgIdTeamTeamIdChannelChannelIdRoute:
    OrgOrgIdTeamTeamIdChannelChannelIdRoute,
}

const OrgOrgIdTeamTeamIdRouteWithChildren =
  OrgOrgIdTeamTeamIdRoute._addFileChildren(OrgOrgIdTeamTeamIdRouteChildren)

interface OrgOrgIdRouteChildren {
  OrgOrgIdTeamTeamIdRoute: typeof OrgOrgIdTeamTeamIdRouteWithChildren
}

const OrgOrgIdRouteChildren: OrgOrgIdRouteChildren = {
  OrgOrgIdTeamTeamIdRoute: OrgOrgIdTeamTeamIdRouteWithChildren,
}

const OrgOrgIdRouteWithChildren = OrgOrgIdRoute._addFileChildren(
  OrgOrgIdRouteChildren,
)

interface OrgRouteChildren {
  OrgOrgIdRoute: typeof OrgOrgIdRouteWithChildren
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgOrgIdRoute: OrgOrgIdRouteWithChildren,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrgRoute: OrgRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
