/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubmitImport } from './routes/submit'
import { Route as SearchImport } from './routes/search'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as UUsernameImport } from './routes/u.$username'
import { Route as RSubredditImport } from './routes/r.$subreddit'
import { Route as SubredditsCreateImport } from './routes/subreddits/create'
import { Route as RSubredditCommentsPostIdImport } from './routes/r.$subreddit.comments.$postId'

// Create Virtual Imports

// Create/Update Routes

const SubmitRoute = SubmitImport.update({
  path: '/submit',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UUsernameRoute = UUsernameImport.update({
  path: '/u/$username',
  getParentRoute: () => rootRoute,
} as any)

const RSubredditRoute = RSubredditImport.update({
  path: '/r/$subreddit',
  getParentRoute: () => rootRoute,
} as any)

const SubredditsCreateRoute = SubredditsCreateImport.update({
  path: '/subreddits/create',
  getParentRoute: () => rootRoute,
} as any)

const RSubredditCommentsPostIdRoute = RSubredditCommentsPostIdImport.update({
  path: '/r/$subreddit/comments/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitImport
      parentRoute: typeof rootRoute
    }
    '/r/$subreddit': {
      id: '/r/$subreddit'
      path: '/r/$subreddit'
      fullPath: '/r/$subreddit'
      preLoaderRoute: typeof RSubredditImport
      parentRoute: typeof rootRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameImport
      parentRoute: typeof rootRoute
    }
    '/subreddits/create': {
      id: '/subreddits/create'
      path: '/subreddits/create'
      fullPath: '/subreddits/create'
      preLoaderRoute: typeof SubredditsCreateImport
      parentRoute: typeof rootRoute
    }
    '/r/$subreddit/comments/$postId': {
      id: '/r/$subreddit/comments/$postId'
      path: '/r/$subreddit/comments/$postId'
      fullPath: '/r/$subreddit/comments/$postId'
      preLoaderRoute: typeof RSubredditCommentsPostIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
  RegisterRoute,
  SearchRoute,
  SubmitRoute,
  RSubredditRoute,
  UUsernameRoute,
  SubredditsCreateRoute,
  RSubredditCommentsPostIdRoute,
})

/* prettier-ignore-end */
