/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SubredditsCreateRouteImport } from './routes/subreddits/create'
import { Route as RSubredditRouteImport } from './routes/r.$subreddit'
import { Route as RSubredditCommentsPostIdRouteImport } from './routes/r.$subreddit.comments.$postId'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SubredditsCreateRoute = SubredditsCreateRouteImport.update({
  id: '/subreddits/create',
  path: '/subreddits/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RSubredditRoute = RSubredditRouteImport.update({
  id: '/r/$subreddit',
  path: '/r/$subreddit',
  getParentRoute: () => rootRouteImport,
} as any)
const RSubredditCommentsPostIdRoute =
  RSubredditCommentsPostIdRouteImport.update({
    id: '/comments/$postId',
    path: '/comments/$postId',
    getParentRoute: () => RSubredditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/r/$subreddit': typeof RSubredditRouteWithChildren
  '/subreddits/create': typeof SubredditsCreateRoute
  '/u/$username': typeof UUsernameRoute
  '/r/$subreddit/comments/$postId': typeof RSubredditCommentsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/r/$subreddit': typeof RSubredditRouteWithChildren
  '/subreddits/create': typeof SubredditsCreateRoute
  '/u/$username': typeof UUsernameRoute
  '/r/$subreddit/comments/$postId': typeof RSubredditCommentsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/r/$subreddit': typeof RSubredditRouteWithChildren
  '/subreddits/create': typeof SubredditsCreateRoute
  '/u/$username': typeof UUsernameRoute
  '/r/$subreddit/comments/$postId': typeof RSubredditCommentsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/submit'
    | '/r/$subreddit'
    | '/subreddits/create'
    | '/u/$username'
    | '/r/$subreddit/comments/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/submit'
    | '/r/$subreddit'
    | '/subreddits/create'
    | '/u/$username'
    | '/r/$subreddit/comments/$postId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/submit'
    | '/r/$subreddit'
    | '/subreddits/create'
    | '/u/$username'
    | '/r/$subreddit/comments/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SubmitRoute: typeof SubmitRoute
  RSubredditRoute: typeof RSubredditRouteWithChildren
  SubredditsCreateRoute: typeof SubredditsCreateRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subreddits/create': {
      id: '/subreddits/create'
      path: '/subreddits/create'
      fullPath: '/subreddits/create'
      preLoaderRoute: typeof SubredditsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$subreddit': {
      id: '/r/$subreddit'
      path: '/r/$subreddit'
      fullPath: '/r/$subreddit'
      preLoaderRoute: typeof RSubredditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$subreddit/comments/$postId': {
      id: '/r/$subreddit/comments/$postId'
      path: '/comments/$postId'
      fullPath: '/r/$subreddit/comments/$postId'
      preLoaderRoute: typeof RSubredditCommentsPostIdRouteImport
      parentRoute: typeof RSubredditRoute
    }
  }
}

interface RSubredditRouteChildren {
  RSubredditCommentsPostIdRoute: typeof RSubredditCommentsPostIdRoute
}

const RSubredditRouteChildren: RSubredditRouteChildren = {
  RSubredditCommentsPostIdRoute: RSubredditCommentsPostIdRoute,
}

const RSubredditRouteWithChildren = RSubredditRoute._addFileChildren(
  RSubredditRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SubmitRoute: SubmitRoute,
  RSubredditRoute: RSubredditRouteWithChildren,
  SubredditsCreateRoute: SubredditsCreateRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
