// This file is auto-generated by @tanstack/router-vite-plugin
// You can manually create this file if auto-generation doesn't work

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router';

import { Route as RootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as LoginRoute } from './routes/login';
import { Route as RegisterRoute } from './routes/register';
import { Route as CreateRoute } from './routes/create';
import { Route as AuctionRoute } from './routes/auction.$auctionId';
import { Route as MyAuctionsRoute } from './routes/my-auctions';
import { Route as WatchlistRoute } from './routes/watchlist';
import { Route as NotificationsRoute } from './routes/notifications';
import { Route as AdminRoute } from './routes/admin';

const rootRoute = RootRoute;

const indexRoute = IndexRoute._addFileChildren([]);
const loginRoute = LoginRoute._addFileChildren([]);
const registerRoute = RegisterRoute._addFileChildren([]);
const createRoute = CreateRoute._addFileChildren([]);
const auctionRoute = AuctionRoute._addFileChildren([]);
const myAuctionsRoute = MyAuctionsRoute._addFileChildren([]);
const watchlistRoute = WatchlistRoute._addFileChildren([]);
const notificationsRoute = NotificationsRoute._addFileChildren([]);
const adminRoute = AdminRoute._addFileChildren([]);

export const routeTree = rootRoute._addFileChildren([
  indexRoute,
  loginRoute,
  registerRoute,
  createRoute,
  auctionRoute,
  myAuctionsRoute,
  watchlistRoute,
  notificationsRoute,
  adminRoute,
]);
